# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  android: circleci/android@1.0.3
  
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:  
    # These next lines define the Android machine image executor: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine

    steps:
      # Checkout the code as the first step.
      - checkout

      # make gradlew startable
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      # And finally run the release build
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease    
            
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
          
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /home/circleci/project/app/build/outputs/apk/release/
          # Must be relative path from root
          paths:
            - app-release-unsigned.apk
     
         
  publish-github-release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at:  /home/circleci/project/app/build/outputs/apk/release/
        - run:
            name: "Publish Release on GitHub"
            command:  ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v0.0.$CIRCLE_BUILD_NUM /home/circleci/project/app/build/outputs/apk/release/
              #VERSION=$(my-binary --version)
              #ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /home/circleci/project/app/build/outputs/apk/release/


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample: 
    jobs:
      - build-and-test
      - publish-github-release:
          requires:
            - build-and-test
